billing/config/routes.rb
Rails.application.routes.draw do
  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'
  get '/auth/:provider/callback', to: 'sessions#create'

  resources :accounts_balances, only: :index
  resources :balances, only: :show
  resources :balance_cycles, only: [] do
    post :close, on: :collection
  end

  root to: 'accounts_balances#index'
end

billing/app/models/account.rb
class Account < ApplicationRecord
  has_many :tasks
  has_one :balance
  has_many :transactions

  def admin?
    role == 'admin'
  end

  def accountant?
    role == 'accountant'
  end
end

billing/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

billing/app/models/balance.rb
class Balance < ApplicationRecord
  belongs_to :account
  has_many :transactions
end

billing/app/models/balance_cycle.rb
class BalanceCycle < ApplicationRecord
  cattr_accessor :current

  has_many :transactions

  enum state: { open: 'open', closed: 'closed' }

  validates :closed_at, presence: true, if: :closed?
  before_create :can_be_only_one_open_cycle

  before_create do
    self.opened_at = Time.current
  end

  def self.current_cycle
    self.current ||= (open.first || create)
  end

  private

  def can_be_only_one_open_cycle
    return if self.class.open.count.zero?

    errors.add(:only_one_open_cycle, 'can be only one open cycle at the moment')
  end
end

billing/app/models/task.rb
class Task < ApplicationRecord
  belongs_to :account

  enum status: { bird_in_a_cage: 'bird_in_a_cage', millet_in_a_bowl: 'millet_in_a_bowl' }
end

billing/app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :balance
  belongs_to :task, optional: true
  belongs_to :balance_cycle

  enum kind: { accrual: 'accrual',  withdrawal: 'withdrawal' }
end

billing/app/controllers/accounts_balances_controller.rb
class AccountsBalancesController < ApplicationController
  before_action :authenticate!
  before_action :authorize!
  helper_method :calculate_balance_for_current_cycle

  def index
    @accounts = Account.preload(balance: :transactions)

  end

  private

  def calculate_balance_for_current_cycle(account)
    account
      .balance
      .transactions
      .select { |transaction| transaction.balance_cycle_id == BalanceCycle.current_cycle.id }
      .sum { |transaction| transaction.withdrawal? ? -transaction.amount : transaction.amount }
  end

  def authorize!
    return if current_account.admin? || current_account.accountant?

    redirect_to root_path, alert: 'Not authorized'
  end
end

billing/app/controllers/balance_cycles_controller.rb
class BalanceCyclesController < ApplicationController
  def close
    CloseBalanceCycleAndOpenNewService.call

    redirect_to root_path
  end
end

billing/app/controllers/balances_controller.rb
class BalancesController < ApplicationController
  def show
    @balance = Balance.preload(:account, transactions: :task).find(params[:id])
  end
end

billing/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    account = Account.find_by(public_id: auth_hash['info']['public_id'])
    session[:account] = account

    redirect_to root_path
  end

  def destroy
    session[:account] = nil

    redirect_to login_pathа
  end

  private

  def auth_hash
    request.env['omniauth.auth']
  end
end

billing/app/helpers/application_helper.rb
module ApplicationHelper
end

billing/app/views/accounts_balances/index.html.erb
<h1>Top Managers Income: <%= TopManagersIncomeService.calculate %></h1>

<h1>Account Balances</h1>

<table>
  <thead>
    <tr>
      <th>Public id</th>
      <th>Full name</th>
      <th>Email</th>
      <th>Role</th>
      <th>Balance</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= account.public_id %></td>
        <td><%= account.full_name %></td>
        <td><%= account.email %></td>
        <td><%= account.role %></td>
        <td><%= calculate_balance_for_current_cycle(account) %></td>
        <td><%= link_to 'Audit', balance_path(account.balance) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

billing/app/views/balances/show.html.erb
<h1><%= @balance.account.full_name %> balance</h1>

<h1>Transactions</h1>

<h3>Your balance is: <%= @balance.amount %></h3>

<table>
  <thead>
    <tr>
      <th>Created at</th>
      <th>Task</th>
      <th>Amount</th>
    </tr>
  </thead>

  <tbody>
    <% @balance.transactions.each do |transaction| %>
      <tr>
        <td><%= transaction.created_at.strftime('%d-%m-%Y %H:%M:%S') %></td>
        <td><%= transaction.task&.title %></td>
        <td style="color:<%= transaction.kind == 'accrual' ? 'green' : 'red' %>"><%= transaction.amount %></td>
      </tr>
    <% end %>
  </tbody>
</table>

billing/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Billing</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>

    <% if current_account %>
      <br/>
      <%= link_to 'Logout', logout_path %>

      <h2>Current account</h2>
      <%= current_account.as_json %>
      <br/>

      <% if current_account.admin? %>
        <h3>Current balance cycle</h3>
        <%= BalanceCycle.current_cycle.as_json %>
        <br/>
        <%= link_to 'Close cycle', close_balance_cycles_path, method: :post %>
      <br/>
      <% end %>
    <% end %>

    <%= yield %>
  </body>
</html>