tracker/config/routes.rb
Rails.application.routes.draw do
  root to: 'tasks#index'

  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'
  get '/auth/:provider/callback', to: 'sessions#create'

  resources :tasks, only: %i[index show new create] do
    post :pour_millet_into_a_bowl, on: :member

    collection do
      post :catch_birds
      get :my
    end
  end
end

tracker/app/models/account.rb
class Account < ApplicationRecord
  has_many :tasks

  validates :email, presence: true, uniqueness: true

  def admin?
    role == 'admin'
  end

  def manager?
    role == 'manager'
  end
end

tracker/app/models/task.rb
class Task < ApplicationRecord
  include AASM

  belongs_to :account

  validates_presence_of :title, :description
  validate :title_without_jira_id

  enum status: {
    bird_in_a_cage: 'open',
    millet_in_a_bowl: 'closed'
  }

  aasm(:status) do
    state :bird_in_a_cage, initial: true
    state :millet_in_a_bowl

    event :pour_millet_into_a_bowl do
      transitions from: :bird_in_a_cage, to: :millet_in_a_bowl
    end
  end

  private

  def title_without_jira_id
    if title.include?('[') || title.include?(']')
      errors.add(:title, "can't include '[' or ']'")
    end
  end
end

tracker/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  private

  attr_reader :current_account

  helper_method :current_account

  def authenticate!
    if session[:account].blank?
      @current_account = nil
      return redirect_to(login_path)
    end
    return if @current_account

    @current_account = Account.find_by(public_id: session[:account]['public_id'])
  end
end

tracker/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    account = Account.find_by(public_id: auth_hash['info']['public_id'])
    session[:account] = account

    redirect_to root_path
  end

  def destroy
    session[:account] = nil

    redirect_to login_path
  end

  private

  def auth_hash
    request.env['omniauth.auth']
  end
end

tracker/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate!
  before_action :set_task, only: [:show, :destroy, :pour_millet_into_a_bowl]
  before_action :can_assign_tasks?, only: :assign_tasks

  # GET /tasks
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # POST /tasks
  def create
    performer = Account.all.sample
    @task = Task.new(task_params.merge(account_id: performer.id))

    if @task.save
      # CUD event
      event_data = {
        public_id: @task.reload.public_id,
        jira_id: @task.jira_id,
        title: @task.title,
        description: @task.description,
        status: @task.status,
        performer_public_id: performer.public_id
      }
      event = ::Event.new(name: 'Task.Created', data: event_data, version: 2)

      validation = SchemaRegistry.validate_event(event.to_h.as_json, 'task.created', version: 2)
      raise StandardError, "Event validation failed:\n#{validation.failure.join("\n")}" if validation.failure?

      WaterDrop::SyncProducer.call(event.to_json, topic: 'tasks-stream')

      event_data = { public_id: @task.public_id, performer_public_id: performer.public_id }
      event = ::Event.new(name: 'Task.BirdCaught', data: event_data)

      validation = SchemaRegistry.validate_event(event.to_h.as_json, 'task.bird_caught', version: 1)
      raise StandardError, "Event validation failed:\n#{validation.failure.join("\n")}" if validation.failure?
      WaterDrop::SyncProducer.call(event.to_json, topic: 'tasks')

      redirect_to @task, notice: 'Task was successfully created.'
    else
      render :new
    end
  end

  def catch_birds
    CatchBirdService.call(Task.bird_in_a_cage, Account.all)

    redirect_to tasks_path, notice: 'Bird caged.'
  end

  def my
    @tasks = Task.where(account_id: current_account.id)
  end

  def pour_millet_into_a_bowl
    if @task.may_pour_millet_into_a_bowl? && @task.pour_millet_into_a_bowl!
      # BE + CUD events
      event = Event.new(name: 'Task.MilletPoured', data: { public_id: @task.public_id })

      validation = SchemaRegistry.validate_event(event.to_h.as_json, 'task.millet_poured', version: 1)
      raise StandardError, "Event validation failed:\n#{validation.failure.join("\n")}" if validation.failure?

      WaterDrop::SyncProducer.call(event.to_json, topic: 'tasks')

      redirect_to @task, notice: 'Millet poured into a bowl.'
    else
      render :show
    end
  end

  # DELETE /tasks/1
  def destroy
    @task.destroy
    redirect_to tasks_url, notice: 'Task was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_task
    @task = Task.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def task_params
    params.require(:task).permit(:jira_id, :title, :description)
  end

  def can_assign_tasks?
    current_account&.admin? || current_account&.manager?
  end
  helper_method :can_assign_tasks?
end

tracker/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <% if current_account %>
      <%= link_to 'Logout', logout_path %>

      <h2>Current account</h2>
      <%= current_account.as_json %>
      <br>
    <% end %>

    <%= yield %>
  </body>
</html>

tracker/app/views/tasks/_form.html.erb
<%= form_for @task do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :jira_id %>
    <%= form.text_area :jira_id %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

tracker/app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tasks</h1>

<%= link_to 'New Task', new_task_path %>
<br>

<% if can_assign_tasks? %>
  <%= link_to 'Assign tasks', catch_birds_tasks_path, method: :post %>
  <br>
<% end %>
<%= link_to 'My Tasks', my_tasks_path %>
<br>

<table>
  <thead>
  <tr>
    <th>Public</th>
    <th>Jira ID</th>
    <th>Title</th>
    <th>Description</th>
    <th>Status</th>
    <th>Account</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @tasks.each do |task| %>
    <tr>
      <td><%= task.public_id %></td>
      <td><%= task.jira_id %></td>
      <td><%= task.title %></td>
      <td><%= task.description %></td>
      <td><%= task.status %></td>
      <td><%= task.account&.full_name %></td>
      <td><%= link_to 'Show', task %></td>
      <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

tracker/app/views/tasks/my.html.erb
<%= link_to 'All Tasks', tasks_path %>
<br>

<table>
  <thead>
  <tr>
    <th>Public</th>
    <th>Title</th>
    <th>Description</th>
    <th>Status</th>
    <th>Account</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @tasks.each do |task| %>
    <tr>
      <td><%= task.public_id %></td>
      <td><%= task.title %></td>
      <td><%= task.description %></td>
      <td><%= task.status %></td>
      <td><%= task.account&.full_name %></td>
      <td><%= link_to 'Close', pour_millet_into_a_bowl_task_path(task), method: :post %></td>
    </tr>
  <% end %>
  </tbody>
</table>

tracker/app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>
<%= link_to 'Back', tasks_path %>

tracker/app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Public:</strong>
  <%= @task.public_id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @task.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Status:</strong>
  <%= @task.status %>
</p>

<p>
  <strong>Account:</strong>
  <%= @task.account_id %>
</p>

<%= link_to 'Close', pour_millet_into_a_bowl_task_path(@task), method: :post %> |
<%= link_to 'Back', tasks_path %>